In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
print(A.shape)
B = np.array([[5, 6], [7, 8]])
print(B.shape)
np.dot(A, B)

(2, 2)
(2, 2)


array([[19, 22],
       [43, 50]])

* `np.dot()` 은 입력이 1차원 배열이면 벡터를, 2차원 배열이면 행렬 곱을 계산함
* `np.dot(A, B)`와 `np.dot(B, A)`는 다른 값이 될 수 있음

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)
np.dot(A, B)

(2, 3)
(3, 2)


array([[22, 28],
       [49, 64]])

In [4]:
C = np.array([[1, 2], [3, 4]])
print(C.shape)
print(A.shape)
np.dot(A, C)

(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

* 행렬의 형상에 주의해야 함
* 행렬 A의 1번째 차원의 원소 수(열 개수)와 행렬 B의 0번째 차원의 원소 수(행 개수)가 같아야 함.

In [5]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A.shape)
B = np.array([7, 8])
print(B.shape)
np.dot(A, B)

(3, 2)
(2,)


array([23, 53, 83])

In [6]:
X = np.array([1, 2])
print(X.shape)
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W.shape)
Y = np.dot(X, W)
Y

(2,)
(2, 3)


array([ 5, 11, 17])