# Numpy

## `ndarray`: numpy dimensional array

* numpy는 `np.array` 함수를 이용하여 배열 생성 → `ndarray`
* numpy는 하나의 데이터 타입만 배열에 넣을 수 있음
  * 리스트와 가장 큰 차이점: Dynamic typing not supported
* C의 Array를 사용하여 배열 생성

In [1]:
import numpy as np

test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [2]:
# shape: numpy array object의 dimension 구성을 반환
test_array.shape

(4,)

In [3]:
# dtype: numpy array의 데이터 타입을 반환
test_array.dtype

dtype('float64')

### Array shape (vector)
* Array (vector, matrix, tensor)의 크기, 형태 등에 대한 정보

In [4]:
test_array = np.array([1, 4, 5, '8'], float)
# string type의 데이터를 입력하여도 float으로 자동 형변환됨
test_array
# ndarray의 구성: array([1., 4., 5., 8.])
# ndarray의 shape(type: tuple): (4,) → 1차원에 4개의 element가 있는 벡터

array([1., 4., 5., 8.])

### Array shape (matrix)

In [5]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

### Array shape (3rd order tensor)

In [6]:
# 3차원 데이터
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor, int).shape
# (4, 3, 4) (대각선 층 개수, row, column)

(4, 3, 4)

### Array shape - `ndim` & `size`

* `ndim`: number of dimension
* `size`: 데이터 개수

In [7]:
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]

print(np.array(tensor, int).ndim)
print(np.array(tensor, int).size)

3
48


### Array `dtype`

* `ndarray`의 single element가 가지는 데이터 타입
* 각 element가 차지하는 메모리 크기 결정

In [8]:
# 데이터 타입을 integer로 선언
np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 데이터 타입을 float로 선언
np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

* 넘파이의 데이터 타입은 C의 데이터 타입과 호환됨

* `nbytes`: ndarray object의 메모리 크기를 반환함

In [10]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float32).nbytes
# (32bits = 4bytes) 4bytes * 6

24

In [11]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.int8).nbytes
# (8bits = 1byte) 1byte * 6

6

In [12]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float64).nbytes
# (64bits = 8bytes) 8bytes * 6

48